# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 10 - Numpy - Operações Aritméticas entre Arrays e Matrizes

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Operações Aritméticas entre Arrays e Matrizes

## Aritmética Entre Arrays
### Adição
A função add() soma o conteúdo de duas matrizes e retorna os resultados em uma nova matriz.


In [1]:
import numpy as np

arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.add(arr1, arr2)

print(novo_array)

print(arr1 + arr2)

[300 320 340 360 380 400]
[300 320 340 360 380 400]


## Subtração
A função subtract() subtrai os valores de uma matriz com os valores de outra matriz e retorna os resultados em uma nova matriz.


In [2]:
import numpy as np


arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.subtract(arr1, arr2)

print(novo_array)

print(arr1 - arr2)

[-100 -100 -100 -100 -100 -100]
[-100 -100 -100 -100 -100 -100]


## Multiplicação
A função multiply() multiplica os valores de uma matriz com os valores de outra matriz e retorna os resultados em uma nova matriz.

In [3]:
import numpy as np


arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.multiply(arr1, arr2)

print(novo_array)

[20000 23100 26400 29900 33600 37500]


## Divisão
A função divide() divide os valores de uma matriz com os valores de outra matriz e retorna os resultados em uma nova matriz.

In [4]:
import numpy as np

arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.divide(arr2, arr1)

print(novo_array)

[2.         1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]


## Potenciação
A função power() eleva os valores da primeira matriz à potência dos valores da segunda matriz e retorna os resultados em uma nova matriz.

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 2, 2, 3, 3, 3])

novo_array = np.power(arr1, arr2)

print(novo_array)

[   100    400    900  64000 125000 216000]


## Resto da Divisão
As funções mod() e as remainder() retornar o resto da divisão da primeira matriz pela segunda matriz, e devolver os resultados de uma nova matriz.

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 4, 6, 7, 9])

novo_array = np.mod(arr1, arr2)

print(novo_array)

[0 0 2 4 1 6]


In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 4, 6, 7, 9])

novo_array = np.remainder(arr1, arr2)

print(novo_array)

[0 0 2 4 1 6]


## Quociente e Resto da Divisão
A divmod()função retorna o quociente e o mod em dois arrays.
O primeiro array contém o quociente e o segundo array contém o resto.


In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 4, 6, 7, 9])

novo_array = np.divmod(arr1, arr2)

print(novo_array)

(array([5, 4, 7, 6, 7, 6], dtype=int32), array([0, 0, 2, 4, 1, 6], dtype=int32))


## Valores absolutos
As funções absolute()e as abs() servem para eliminar o sinal negativo dos valores.

In [9]:
import numpy as np

meu_array = np.array([-10, -34, 11, 32, 34 -65])

novo_array = np.absolute(meu_array)

print(novo_array)

[10 34 11 32 31]


## Arredondamento de Casas Decimais

###Truncamento
Remove os decimais e retorna o número flutuante menor mais próximo de zero

In [10]:
import numpy as np

meu_array = np.trunc([-12.234234, 54.12315])

print(meu_array)

[-12.  54.]


Exemplo
Mesmo exemplo, usando fix():

In [11]:
import numpy as np

meu_array = np.fix([-12.234234, 54.12315])

print(meu_array)

[-12.  54.]


## Arredondamento
A função around() incrementa o dígito anterior ou decimal em 1 se> = 5, caso contrário, não fará nada.


In [12]:
import numpy as np

meu_array = np.around([-12.57734234, 54.12315], 2)

print(meu_array)

[-12.58  54.12]


A função floor () arredonda o decimal para o inteiro inferior mais próximo.


In [13]:
import numpy as np

meu_array = np.floor([-12.234234, 54.12315])

print(meu_array)

[-13.  54.]


A função ceil () arredonda o decimal para o inteiro superior mais próximo.

In [14]:
import numpy as np

meu_array = np.ceil([-12.234234, 54.12315])

print(meu_array)

[-12.  55.]


## Soma de Matrizes
Some os valores em arr1 e os valores em arr2:

In [15]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

novo_array = np.sum([arr1, arr2])

print(novo_array)

300


# Soma sobre determinado eixo
axis = 0 zero para somar as colunas
axis = 1 para somar linhas

In [16]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

novo_array = np.sum([arr1, arr2], axis=1)

print(novo_array)

[150 150]


In [17]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

novo_array = np.sum([arr1, arr2], axis=0)

print(novo_array)

[ 20  40  60  80 100]


## Soma Cumulativa
Soma cumulativa significa adicionar parcialmente os elementos na matriz.


In [18]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50])

novo_array = np.cumsum(meu_array)

print(novo_array)

[ 10  30  60 100 150]


## Produto cumulativo
Produto cumulativo significa retirar o produto parcialmente.


In [19]:
import numpy as np

meu_array = np.array([1, 2, 3, 4, 5])

novo_array = np.cumprod(meu_array)

print(novo_array)

[  1   2   6  24 120]


## Diferenças 
Uma diferença discreta significa subtrair dois elementos sucessivos.


In [20]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50])

acum_array = np.cumsum(meu_array)

print(acum_array)

dif_array = np.diff(acum_array)

print(dif_array)

[ 10  30  60 100 150]
[20 30 40 50]


# Operações de conjunto (Coleção de elementos únicos)

Usa dos para operações de intersecção, união e diferença.
O método unique() do NumPy para encontrar elementos exclusivos de qualquer array. 

In [21]:
import numpy as np

meu_array = np.array([12, 12, 12, 22, 23, 24, 25, 25, 26, 27])

x = np.unique(meu_array)

print(x)

[12 22 23 24 25 26 27]


### Encontrando União


In [22]:
import numpy as np

conj1 = np.array([21, 22, 23, 24, 25])
conj2 = np.array([23, 24, 25, 26])

novo_array = np.union1d(conj1, conj2)

print(novo_array)

[21 22 23 24 25 26]


### Encontrando intersecção


In [23]:
import numpy as np

conj1 = np.array([21, 22, 23, 24, 25])
conj2 = np.array([23, 24, 25, 26])

novo_array = np.intersect1d(conj1, conj2, assume_unique=True)

print(novo_array)

[23 24 25]


### Encontrando Diferença

Use o método setdiff1d() para encontrar apenas os valores no primeiro conjunto que NÃO estão no segundos.

In [24]:
import numpy as np

conj1 = np.array([21, 22, 23, 24, 25])
conj2 = np.array([23, 24, 25, 26])

novo_array = np.setdiff1d(conj1, conj2, assume_unique=True)

print(novo_array)

[21 22]


#Encontrando Diferença Simétrica
Use o método setxor1d() para encontrar apenas os valores que NÃO estão presentes em AMBOS os conjuntos.

In [25]:
import numpy as np

set1 = np.array([21, 22, 23, 24, 25])
set2 = np.array([23, 24, 25, 26])

novo_array = np.setxor1d(set1, set2, assume_unique=True)

print(novo_array)

[21 22 26]


##  Criar ufunc personalizadas
Definir uma função, como você faz com funções normais em Python, e então adicioná-la à sua biblioteca ufunc NumPy com o método frompyfunc().

O métodofrompyfunc() precisa dos seguintes argumentos:
- function - o nome da função.
- inputs - o número de argumentos de entrada (matrizes).
- outputs - o número de matrizes de saída.


In [26]:
import numpy as np

def adicionar(arr1, arr2):
  return arr1 + arr2

func_adicionar = np.frompyfunc(adicionar, 2, 1)

print(func_adicionar([21, 22, 23, 24], [25, 26, 27, 28]))

[46 48 50 52]


### Como checar se uma função é um ufunc
Verifique o tipo de função para verificar se é ufunc ou não.


In [27]:
import numpy as np
print(type(func_adicionar))
print(type(np.add))
print(type(np.add) == np.ufunc)

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
True


## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/