# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 11 - Numpy - Exportação e Importação de Arrays e Matrizes para Arquivos

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Exportação e Importação de Arrays e Matrizes para Arquivos

## Salvando Arrays em arquivos


In [1]:
import numpy as np
from numpy import random

meu_array =random.randint(10,70, size=(5, 5)) 

print(meu_array)

np.savetxt("array.csv", meu_array, delimiter=";", fmt='%s')

[[54 68 35 29 30]
 [50 15 43 40 21]
 [29 33 37 52 15]
 [54 40 51 28 44]
 [22 13 14 36 49]]


In [2]:
with open("array.csv") as f:
  print(f.read())

54;68;35;29;30
50;15;43;40;21
29;33;37;52;15
54;40;51;28;44
22;13;14;36;49



## Carregando Arrays a partir de Arquivos

In [3]:
import numpy as np
novo_arr = np.loadtxt('array.csv', delimiter=';', skiprows=0 , dtype=float)
print(novo_arr)

[[54. 68. 35. 29. 30.]
 [50. 15. 43. 40. 21.]
 [29. 33. 37. 52. 15.]
 [54. 40. 51. 28. 44.]
 [22. 13. 14. 36. 49.]]


## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/
