# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 08 - Numpy - Geração de Valores Aleatórios em Arrays e Matrizes

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Geração de Valores Aleatórios em Arrays e Matrizes

## Gerando Números Aleatórios com o módulo random
- Número (pseudo) aleatório é aquele que não pode ser previsto logicamente.

### Gerar numeros inteiros aleatórios:


In [1]:
from numpy import random

x = random.randint(30)

print(x)

16


### Gerar matriz de numeros inteiros aleatórios:

In [2]:
from numpy import random

x=random.randint(60, size=(6))

print(x)

[53  6 10 52 51 19]


In [3]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[93 37 50 43 34]
 [81 46 29 90 73]
 [19 97 11 41 71]]


### Gerar flutuação aleatória usando método rand() 
- Esse método retorna uma flutuação aleatória entre 0 e 1.


In [4]:
from numpy import random

x = random.rand()

print(x)

0.3156147514583413


In [5]:
from numpy import random

x = random.rand(5)

print(x)

[0.48075389 0.74153779 0.97886215 0.35476671 0.7827995 ]


In [6]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.33806014 0.01722852 0.52086845 0.0477291  0.24696408]
 [0.91056662 0.56579322 0.91570125 0.81000298 0.28028167]
 [0.42306484 0.12361681 0.96851795 0.08605302 0.40343074]]


### Combinando randint()  e   rand()  para gerar numero float maiores que 1

In [7]:
from numpy import random

x=random.randint(100, size=(5)) + random.rand(5) 

print(x)

[67.90306682 10.24096752 58.56543061 32.99475094 49.07781152]


In [8]:
from numpy import random

x=random.randint(80, 220, size=(3, 5)) + random.rand(3, 5) 

print(x)

[[195.51518741 128.23201128 160.64241846 159.27526931 136.7723105 ]
 [145.71557467 120.03492724 215.78077771  87.20447136 182.83948793]
 [216.54935998 167.12501602 128.61651138 170.49807761 153.06451735]]


### Gerar número aleatório a partir de uma lista predefinida usando método choice()


In [9]:
from numpy import random

x = random.choice([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(x)

20


In [10]:
nomes= [ 'Emanuel', 'Miguel', 'Henry', 'Gael', 'Arthur Henrique', 'Luiz', 
            'José', 'Noah', 'Yago', 'André', 'Felipe', 'Pietro', 'Lucca', 
            'Raul', 'Luiz', 'Fernando', 'Eduardo', 'Ruan', 'Luiz Otávio', 
            'Davi Miguel', 'Rafael', 'Thiago', 'Oliver', 'Rodrigo', 
            'João Gabriel', 'Samuel', 'João Victor', 'Ryan', 'Pedro Miguel', 
            'Bryan', 'Enzo Gabriel', 'Pedro Henrique', 'Augusto', 'Leonardo', 
            'Kauê', 'Davi Lucas', 'Martin', 'Nicolas', 'Bernardo', 
            'Lucas Gabriel', 'Gabriel', 'Miguel Henrique', 'Lorenzo', 'Daniel',
            'Gustavo', 'Caleb', 'Danilo', 'Pedro', 'João Miguel', 'Ian', 
            'Davi', 'Anthony', 'Pedro Lucas', 'Vinícius', 'João', 'Lucas', 
            'Tomás', 'Anthony Gabriel', 'Enzo', 'Bento', 'Benjamin', 'Vicente',
            'Enzo Miguel', 'Théo', 'Fernanda Otávio', 'Matheus', 
            'Levi', 'Benício', 'Victor', 'Joaquim', 'Guilherme', 'Thomas', 
            'Enrico', 'Arthur', 'Carlos', 'Henrique', 'Luiz', 
            'João Guilherme', 'Breno', 'Davi', 'Luiz Henrique', 
            'Murilo', 'Cauã', 'Nathan', 'João Pedro', 'Yuri', 'Victor Hugo', 
            'Antônio', 'Kaique', 'Arthur Miguel', 'João Lucas', 'Caio', 
            'Davi Lucca', 'Arthur', 'Bruno', 'Luan', 'Heitor', 'Francisco', 
            'Isaac', ] 

In [11]:
from numpy import random

x = random.choice(nomes)

print(x)

Gustavo


In [12]:
from numpy import random

x = random.choice(nomes, size=(3, 5))

print(x)

[['Luiz' 'Arthur Henrique' 'Fernanda Otávio' 'Arthur' 'Bento']
 ['João Miguel' 'Arthur' 'Fernanda Otávio' 'Fernanda Otávio'
  'Pedro Miguel']
 ['Bernardo' 'Arthur' 'Luiz Otávio' 'Joaquim' 'Fernando']]


### Permutações aleatórias de elementos shuffle() e permutation()
- shuffle() altera a disposição dos elementos  na própria matriz.


In [13]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

np.random.shuffle(meu_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[100  50  30  70  20  80  60  40  10  90]


- permutation()  retorna uma matriz reorganizada (e deixa a matriz original inalterada)

In [14]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

novo_array = np.random.permutation(meu_array)

print(meu_array)

print(novo_array)


[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 40 100  20  60  50  80  30  90  70  10]


## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/