# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 06 - Numpy - Junção / Segmentação de Arrays e Matrizes

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Junção / Segmentação de Arrays e Matrizes

## Juntando matrizes NumPy com  np.concatenate()
Em NumPy os arrays são unidos por eixos, usando a função concatenate().
Se o eixo não for passado explicitamente, ele será considerado 0.


### Juntando arrays 1-D


In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.concatenate((arr1, arr2))

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


### Juntando matrizes 2-D ao longo das linhas (eixo = 1):

In [2]:
import numpy as np

arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.concatenate((arr1, arr2), axis=1)

print(meu_array)

[[10 20 50 60]
 [30 40 70 80]]


### Juntando matrizes 2-D ao longo das colunas (eixo = 0):

In [3]:
import numpy as np

arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.concatenate((arr1, arr2), axis=0)

print(meu_array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


## Empilhamento de  arrays com  1-D (apenas) np.stack()
- colocá-los um sobre o outro, ou ao lado do outro.

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.stack((arr1, arr2), axis=0)

print(meu_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.stack((arr1, arr2), axis=1)

print(meu_array)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


## Empilhamento de arrays e matrizes ao longo das linhas usando hstack():

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.hstack((arr1, arr2))

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
', '.join([str(x) for x in np.nditer(meu_array)])

'10, 20, 30, 40, 50, 60, 70, 80, 90, 100'

In [8]:
import numpy as np

arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.hstack((arr1, arr2))

print(meu_array)

[[10 20 50 60]
 [30 40 70 80]]


## Empilhamento de arrays e matrizes ao longo das colunas usando vstack()

In [9]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.vstack((arr1, arr2))

print(meu_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [10]:
import numpy as np

arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.vstack((arr1, arr2))

print(meu_array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


## Empilhamento ao longo da altura usanto dstack()

In [11]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.dstack((arr1, arr2))

print(meu_array)

[[[ 10  60]
  [ 20  70]
  [ 30  80]
  [ 40  90]
  [ 50 100]]]


In [12]:
import numpy as np

arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.dstack((arr1, arr2))

print(meu_array)

[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]


## Quebra / Divisão de Matriz e Array  NumPy
### Quebar usando a função array_split()
A função array_split() pode ser usada para dividir matrizes, passamos como argumentos a matriz e o número de divisões.

Caso o numero de elementos não seja multiplo os ultimos array terão menos elementos, mas não ocorrerá erro na operação.

In [13]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(meu_array, 2)

print(novo_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [14]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(meu_array, 3)

print(novo_array)

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]


In [15]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(meu_array, 4)

print(novo_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80]), array([ 90, 100])]


In [16]:
import numpy as np

meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])
novo_array = np.array_split(meu_array, 2)

print(novo_array)

[array([[10, 20],
       [30, 40],
       [50, 60]]), array([[ 70,  80],
       [ 90, 100],
       [110, 120]])]


In [17]:
import numpy as np

meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.array_split(meu_array, 3)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


In [18]:
import numpy as np

meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.array_split(meu_array, 4)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100]]), array([[110, 120]])]


### Quebrar usando a função split() 
Esse método é similar ao  array_split(), mas falha se a quantidad de elementos não for multiplo da quantidade de divisões.

In [19]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.split(meu_array, 2)

print(novo_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [20]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.split(meu_array, 3)

print(novo_array)

ValueError: array split does not result in an equal division

In [21]:
import numpy as np

meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.split(meu_array, 3)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


In [22]:
import numpy as np

meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.split(meu_array, 4)

print(novo_array)

ValueError: array split does not result in an equal division

### Quebrar uma Matriz em arrays de valores das colunas com hsplit()

In [23]:
import numpy as np

meu_array = np.array([[10, 20, 30, 40, 50, 60], 
                      [70, 80, 90, 100, 110, 120], 
                      [130, 140, 150, 160, 170, 180]])

novo_array = np.hsplit(meu_array, 3)

print(novo_array)

[array([[ 10,  20],
       [ 70,  80],
       [130, 140]]), array([[ 30,  40],
       [ 90, 100],
       [150, 160]]), array([[ 50,  60],
       [110, 120],
       [170, 180]])]


### Quebrar uma Matriz em arrays de valores das linhas com vsplit()

In [24]:
import numpy as np

meu_array = np.array([[10, 20, 30], 
                      [40, 50, 60], 
                      [70, 80, 90], 
                      [100, 110, 120], 
                      [130, 140, 150], 
                      [160, 170, 180]])

novo_array = np.vsplit(meu_array, 3)

print(novo_array)

[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]]), array([[130, 140, 150],
       [160, 170, 180]])]


## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/