# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 01 - Numpy - Criação de Arrays e Matrizes

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Criação de Arrays e Matrizes

# NumPy (Numerical Python)
- Biblioteca python usada para trabalhar com álgebra linear, arrays e matrizes.
- Criada em 2005 por Travis Oliphant como projeto de código aberto. 
- Fornecer um objeto de matriz que é até 50x mais rápido que as listas tradicionais do Python
  - Array NumPy é armazenados em um local contínuo na memória;
  - É otimizado para funcionar com as arquiteturas de CPU mais recentes;
  - Utiliza tipos fixos;
  - Demandam menos espaço de memória para mesma quantidade de elementos;
  - SIMD - Processamento vetores Single instruction, multiple data (SIMD);
  - Utilização eficente de cache do processador
  - Mais versatilidade nas operações com arrays (ex. multiplicação)
  - Utilizado como base para calculos matemáticos, Plotagem de gráficos (Matplotlib), backend do pandas, base para algoritmos de machine learning.
- É codificado parcialmente em Python, mas a maioria das partes que requerem computação rápida são escritas em C ou C ++.
- O objeto array em NumPy é chamado ndarray.
- O ndarray fornece várias funções de suporte que facilitam muito se uso.
- São indicados para situações em que velocidade e recursos são muito importantes.

## Importância do Numpy
### Aplicativos Numpy com outras bibliotecas

###NumPy com Pandas

Pandas é uma das bibliotecas mais importantes em Python para análise de dados, fornece recuros de  alto desempenho para tratamento e análise de dados. 
O Dataframe do Pandas utiliza o NumPy para cálculos mais rápidos. 

### NumPy com Matplotlib

É uma ferramenta muito útil para trabalhar com representações gráficas. Consiste em uma ampla gama de funções para traçar gráficos e também manipulá-los. O Matplot utiliza também adota o NumPy entre suas dependencias.

### NumPy com SciPy

Scipy é  biblioteca científica mais importante em python. Ele foi construído sobre as funcionalidades do NumPy, com funcionalidades avançadas no SciPy para cálculos científicos com maior desempenho matemático.


## Instalação de NumPy
Usar o comando 

```
pip install numpy

```


## Importar NumPy
```
import numpy

```


In [1]:
import numpy

meu_array = numpy.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


## Padrão de importação do NumPy com o alias np


In [2]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


## Como checar a versão do NumPy
Acessar o propriedade __version__ do pacote.

In [3]:
import numpy as np

print(np.__version__)

1.21.0


## Criando matrizes
- O objeto de matriz em NumPy é chamado ndarray.
- Usar a função array() para criar a matriz.


In [4]:
import numpy as np

meu_array = np.array([10, 20, 30, '40', 50, 60, 70, 80, 90, 100])

print(meu_array)

print(type(meu_array))

meu_array.dtype

['10' '20' '30' '40' '50' '60' '70' '80' '90' '100']
<class 'numpy.ndarray'>


dtype('<U11')

Pode-se passar  lista, tupla ou qualquer objeto do tipo array para a função array()

### Usando uma tupla para criar uma matriz NumPy:


In [5]:
import numpy as np

meu_array = np.array((10, 20, 30, 40, 50, 60, 70, 80, 90, 100))

print(meu_array)

print(type(meu_array))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


### Usando um set para criar uma matriz NumPy:

In [6]:
import numpy as np

meu_array = np.array({10, 20, 30, 40, 50, 60, 70, 80, 90, 100})

print(meu_array)

print(type(meu_array))

{100, 70, 40, 10, 80, 50, 20, 90, 60, 30}
<class 'numpy.ndarray'>


## Dimensões em matrizes
### Matrizes 0-D
- Matrizes 0-D, ou escalares, são os elementos de uma matriz.
- Cada valor em uma matriz é uma matriz 0-D.


In [7]:
import numpy as np

meu_array = np.array(100)

print(meu_array)

print(type(meu_array))

100
<class 'numpy.ndarray'>


### Matrizes 1-D ou unidimensional
Matriz que possui matrizes 0-D como seus elementos. São os arrays mais comuns e básicos.



In [8]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

print(type(meu_array))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


### Utilizam tipos fixos para todos os elementos
Os tipos serão convertidos para sejam do mesmo tipo


In [9]:
import numpy as np

meu_array = np.array([10, 20, 30, 40.5, 50.5, 60.5, 70.5, 80, 90, 100])

print(meu_array)

print(type(meu_array))

[ 10.   20.   30.   40.5  50.5  60.5  70.5  80.   90.  100. ]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

meu_array = np.array([10, 20, 30, 40.5, 50.5, 60.5, 70.5, '80', '90', '100'])

print(meu_array)

print(type(meu_array))

['10' '20' '30' '40.5' '50.5' '60.5' '70.5' '80' '90' '100']
<class 'numpy.ndarray'>


### Matrizes 2-D
Matriz que possui matrizes 1-D como seus elementos, geralmente usada para representar matrizes.

In [11]:
import numpy as np

meu_array = np.array([
                      [10, 20, 30], 
                      [40, 50, 60]
                      ])

print(meu_array)

print(type(meu_array))

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


## Arrays 3-D
Array que possui arrays 2-D (matrizes) como seus elementos.


In [12]:
import numpy as np

meu_array = np.array([
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ], 
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ]
                      ])

print(meu_array)

print(type(meu_array))

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>


### Obtendo a quantidade de dimensões do array
- Utilize o atributo do objeto ndarray.

In [13]:
import numpy as np

meu_array = np.array(42)

print(meu_array.ndim)


0


In [14]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array.ndim)

1


In [15]:
import numpy as np

meu_array = np.array([
                      [10, 20, 30], 
                      [40, 50, 60]
                      ])

print(meu_array.ndim)

2


In [16]:
import numpy as np

meu_array = np.array([[
                       [10, 20, 30], [40, 50, 60]
                       ], 
                      [
                       [10, 20, 30], [40, 50, 60]
                       ]
                      ])

print(meu_array.ndim)

3


## Matrizes com muitas dimensões
- Uma matriz pode ser criada com qualquer número de dimensões, usando o argumento ndmin.

In [17]:
import numpy as np

meu_array = np.array([21, 22, 23, 24, 25], ndmin=5)

print(meu_array)

print(meu_array.ndim)

[[[[[21 22 23 24 25]]]]]
5


## Criando arrays vazios ou com valores predefinidos

- sem valor indicar valor prededfinido

In [18]:
import numpy as np

meu_array = np.empty((4,))

print(meu_array)

print(meu_array.ndim)


[2.12199579e-314 9.27312161e-312 6.32404027e-321 6.95250701e-310]
1


In [19]:
import numpy as np

meu_array = np.empty((3,3))

print(meu_array)

print(meu_array.ndim)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.45840386e-321]
 [0.00000000e+000 9.27312161e-312 9.27965344e-312]]
2


- indicado 1 como valores

In [20]:
import numpy as np

meu_array = np.ones((3,3))

print(meu_array)

print(meu_array.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


- Indicando 0 zereo como valores

In [21]:
import numpy as np

meu_array = np.zeros((3,5))

print(meu_array)

print(meu_array.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


- Indicando o valor desejado

In [22]:
import numpy as np

meu_array = np.full((3,3), 99)

print(meu_array)

print(meu_array.ndim)


[[99 99 99]
 [99 99 99]
 [99 99 99]]
2


## Adicionando e removendo elementos 
### insert(arr, obj, valores [, eixo])
Insira valores ao longo do eixo fornecido antes dos índices fornecidos.



In [23]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

novo_array = np.insert(meu_array,3,888)

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30 888  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


### append(arr, valores [, eixo])

Acrescente valores ao final de uma matriz.



In [24]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

novo_array = np.append(meu_array,[888,999])

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100 888 999]
[ 10  20  30  40  50  60  70  80  90 100]


### delete(arr, obj [, eixo])

Retorne uma nova matriz com submatrizes ao longo de um eixo excluído.



In [25]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

novo_array = np.delete(meu_array,[3,4,5])

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


### unique(ar [, return_index, return_inverse,…])

Encontre os elementos exclusivos de uma matriz.

In [26]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100,10, 20, 30, 40, 50, 60, 70, 80, 90, 100,10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# print(meu_array)

novo_array = np.unique(meu_array)

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100  10  20  30  40  50  60  70  80
  90 100  10  20  30  40  50  60  70  80  90 100]


## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/