# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 09 - Numpy - Funções Matemáticas e Estatísticas em Arrays e Matrizes

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Funções Matemáticas e Estatísticas em Arrays e Matrizes

## Ufuncs NumPy
- ufuncs são "Funções Universais" que operam no objeto ndarray por meio de vetorização (operação baseada em vetor em vez de iteracao) no NumPy, que é muito mais rápido do que iterar sobre os elementos.

- fornecem transmissão e métodos adicionais, como reduzir, acumular, entre outros.
- aceitam argumentos adicionais, como: where, dtype e out.

- operação baseada em vetor são mais rápidas porque as CPUs modernas são otimizadas para esse tipo de operações.

### Verifique a diferença de tempo de processamento entre uma mesma operação interativa e uma operação vetorial

In [1]:
import numpy as np
x = np.random.randint(100, size=(10**7))
y = np.random.randint(100, size=(10**7))
z = []
print(x.shape)

(10000000,)


In [2]:
%%timeit
for i, j in zip(x, y):
  z.append(i + j)

2.27 s ± 326 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit
z = np.add(x, y)

16.6 ms ± 278 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### O NumPy oferece uma grande quantidade de funções vetorias para diversos fins


- Cálculos matemáticos: https://numpy.org/doc/stable/reference/routines.math.html
- Cálculos estatísticos:  https://numpy.org/doc/stable/reference/routines.statistics.html

- Calculos financeiros: https://numpy.org/doc/stable/reference/routines.financial.html
- Manipulação de texto: https://numpy.org/doc/stable/reference/routines.char.html
- Algebra linear: https://numpy.org/doc/stable/reference/routines.linalg.html

## Exemplo de cálculos matemáticos

- Cálculos matemáticos: https://numpy.org/doc/stable/reference/routines.math.html


#### floor(x, /[, out, where, casting, order, …])
- Retorma o array com valor arrendondados para o inteiro menor

In [4]:
from numpy import random

x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

[[85.21419414 25.21229956 21.36973513  8.08274549 12.03928041]
 [62.19433109 28.7969437  99.77536801 94.5269999  34.61811375]
 [ 0.7356546  77.61916653 83.07410781 71.1770724  94.78265445]]


In [5]:
from numpy import random

x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

print(np.floor(x))

print(x)

[[30.96627386 11.88139795 25.5687027  36.38725652 42.69151225]
 [ 0.19698335 27.33312935 73.97299115 80.72908563 17.20192182]
 [25.03246074  1.3341385  98.11297741 19.38141037 63.80357083]]
[[30. 11. 25. 36. 42.]
 [ 0. 27. 73. 80. 17.]
 [25.  1. 98. 19. 63.]]
[[30.96627386 11.88139795 25.5687027  36.38725652 42.69151225]
 [ 0.19698335 27.33312935 73.97299115 80.72908563 17.20192182]
 [25.03246074  1.3341385  98.11297741 19.38141037 63.80357083]]


In [6]:
import numpy as np


x= np.random.randint(100, size=(3, 5)) + np.random.rand(3, 5) 

print(x)

print(np.floor(x, out=x))

print(x)

[[31.61986397 79.99484409 11.38012316 49.55672057  8.31162864]
 [86.78751053 47.22707273 10.57792309  7.62486934  2.28018371]
 [15.69064545 34.62138951 39.51849289 33.80841723 26.28973441]]
[[31. 79. 11. 49.  8.]
 [86. 47. 10.  7.  2.]
 [15. 34. 39. 33. 26.]]
[[31. 79. 11. 49.  8.]
 [86. 47. 10.  7.  2.]
 [15. 34. 39. 33. 26.]]


In [7]:
from numpy import random

x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

resultado = np.zeros(x.shape)

print(np.floor(x, where=x>50 , out=x))

print(x)

print(resultado)


[[28.68395669 52.04587776 35.41281366 83.85148848 19.96027338]
 [28.46229191 29.48307332 63.57266717 40.87938401 76.04070874]
 [16.07940433  3.87688956  4.00946234 85.3273555  99.48472748]]
[[28.68395669 52.         35.41281366 83.         19.96027338]
 [28.46229191 29.48307332 63.         40.87938401 76.        ]
 [16.07940433  3.87688956  4.00946234 85.         99.        ]]
[[28.68395669 52.         35.41281366 83.         19.96027338]
 [28.46229191 29.48307332 63.         40.87938401 76.        ]
 [16.07940433  3.87688956  4.00946234 85.         99.        ]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### ceil(x, /[, out, where, casting, order, …])

Retorna o inteiro superior

In [8]:
from numpy import random

x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

print(np.ceil(x))


[[73.9543552  66.60288021 12.64685261 49.83296036 99.89922453]
 [ 6.5428475  62.86548304 94.38727239 23.31552444 12.29109343]
 [87.11116915 22.48609099 92.3098061   6.62134422  1.40953927]]
[[ 74.  67.  13.  50. 100.]
 [  7.  63.  95.  24.  13.]
 [ 88.  23.  93.   7.   2.]]


### prod(a[, axis, dtype, out, keepdims, …])
- Retorna o produto dos elementos de um array no eixo informado

In [9]:
# Produto das colunas
from numpy import random

a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.prod(a,axis=0))

[[4 4]
 [4 4]
 [3 2]]
[48 32]


In [10]:
# Produto das linhas
from numpy import random

a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.prod(a,axis=1))

[[4 1]
 [4 4]
 [3 3]]
[ 4 16  9]


### sum(a[, axis, dtype, out, keepdims, …])
Retorna a soma dos elementos do array para o eixo escolhido

In [11]:
# soma das colunas
from numpy import random

a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.sum(a,axis=0))

[[3 3]
 [1 3]
 [1 3]]
[5 9]


In [12]:
# soma das linhas
from numpy import random

a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.sum(a,axis=1))

[[3 4]
 [1 1]
 [4 1]]
[7 2 5]


### exp(x, /[, out, where, casting, order, …])
- Retorna o exponencial dos elementos de um array (e=2.718281)

In [13]:
from numpy import random

a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.exp(a))



[[1 2]
 [2 3]
 [3 2]]
[[ 2.71828183  7.3890561 ]
 [ 7.3890561  20.08553692]
 [20.08553692  7.3890561 ]]


### log10(x, /[, out, where, casting, order, …])
- Retorna o logarítimo na base 10 dos elementos do array

In [14]:
from numpy import random

a=random.randint(1000,2000, size=(3, 2)) 

print(a)

print(np.log10(a))



[[1704 1708]
 [1662 1339]
 [1718 1716]]
[[3.23146959 3.23248787]
 [3.22063102 3.12678058]
 [3.23502316 3.23451728]]


## Exemplo de cálculos estatísticos

- Cálculos estatísticos:  https://numpy.org/doc/stable/reference/routines.statistics.html

### amin(a[, axis, out, keepdims, initial, where])
- Retorna o menor valor do array para o eixo informado

In [15]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.amin(a, axis=0))

print(np.amin(a, axis=1))

[[35 33 13 62 22]
 [42 60 64 37 27]
 [11 18 50 18 67]
 [26 65 26 57 47]
 [36 22 62 68 20]]
[11 18 13 18 20]
[13 27 11 26 20]


### amax(a[, axis, out, keepdims, initial, where])
- Retorna o maior valor do array para o eixo informado

In [16]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.amax(a, axis=0))

print(np.amax(a, axis=1))

[[32 22 62 18 44]
 [52 29 23 57 69]
 [50 59 44 55 20]
 [64 65 62 53 37]
 [68 59 45 42 66]]
[68 65 62 57 69]
[62 69 59 65 68]


### median(a[, axis, out, overwrite_input, keepdims])
- Retorna a mediana dos valores do array para o eixo informado

In [17]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.median(a, axis=0))

print(np.median(a, axis=1))

[[29 53 49 23 25]
 [37 63 22 25 58]
 [16 54 18 67 35]
 [64 25 43 39 35]
 [54 50 33 30 30]]
[37. 53. 33. 30. 35.]
[29. 37. 35. 39. 33.]


### average(a[, axis, weights, returned])
- Retorna a media ponderada dos valores do array para o eixo informado

In [18]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 
print(a)

print('media coluna',np.average(a, axis=0))

print('media linha',np.average(a, axis=1))

pesos = random.randint(1,5, size=(5, 5)) 

print('pesos',pesos)

print('media ponderada coluna',np.average(a, axis=0, weights=pesos))

print('media ponderada linha',np.average(a, axis=1, weights=pesos))


[[39 49 25 56 29]
 [65 58 48 36 26]
 [10 43 62 19 34]
 [52 15 13 28 68]
 [58 39 52 43 35]]
media coluna [44.8 40.8 40.  36.4 38.4]
media linha [39.6 46.6 33.6 35.2 45.4]
pesos [[3 1 4 1 4]
 [3 2 4 1 3]
 [2 1 1 3 1]
 [4 4 2 4 3]
 [1 4 1 1 1]]
media ponderada coluna [46.         35.33333333 36.         30.4        38.91666667]
media ponderada linha [33.69230769 47.46153846 27.         35.88235294 43.        ]


### mean(a[, axis, dtype, out, keepdims])
- Retorna a media aritmética dos valores do array para o eixo informado

In [19]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.mean(a, axis=0))

print(np.mean(a, axis=1))

[[13 66 19 46 22]
 [40 49 47 57 39]
 [60 38 50 25 44]
 [10 21 37 36 28]
 [33 31 50 11 14]]
[31.2 41.  40.6 35.  29.4]
[33.2 46.4 43.4 26.4 27.8]


### std(a[, axis, dtype, out, ddof, keepdims])
- Retorna a desvio-padrao dos valores do array para o eixo informado

In [20]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.std(a, axis=0))

print(np.std(a, axis=1))

[[59 59 13 65 65]
 [64 45 36 17 45]
 [65 17 63 40 55]
 [27 44 62 68 25]
 [54 21 47 13 23]]
[13.96280774 15.82908715 18.5407659  23.08765904 16.4632925 ]
[19.78282083 15.23942256 17.82133553 17.56587601 15.94490514]


### var(a[, axis, dtype, out, ddof, keepdims])
- Retorna a variância dos valores do array para o eixo informado

In [21]:
from numpy import random

a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.var(a, axis=0))

print(np.var(a, axis=1))

[[66 41 28 12 10]
 [39 35 49 48 51]
 [68 30 65 23 12]
 [21 69 68 19 10]
 [63 15 40 48 32]]
[340.24 314.4  226.8  228.4  264.8 ]
[427.04  39.04 516.24 658.64 256.24]


## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/