# 02 - Numpy - Computação Vetorial e Matricial
## Aula 09 - 04 - Numpy - Forma e Remodelagem de Matrizes (shape)

## Professor: Orlando Oliveira dos Santos, MsC.
 - E-mail: professor.orlando.santos@gmail.com 
 - Youtube :https://www.youtube.com/channel/UCPWWbkPWFmOjXH50TQWNAYg
 - Linkedin: https://linkedin.com/in/orlandoosantos
 - Facebook: https://www.facebook.com/proforlandosantosmsc/
 - Twitter: https://twitter.com/ProfOrlandoMsC
 - Instagram: https://www.instagram.com/proforlandosantosmsc/



## Formação Acadêmica
- Mestrado em Computação Aplicada - UnB (2014 – 2016)	
- MBA, Administração Estratégica de Sistemas de Informação – FGV (2011 – 2013)
- Tecnólogo em Processamento de Dados, Análise e Desenvolvimento de Sistemas – FAETEC/SP (2000-2002)

# Numpy - Forma e Remodelagem de Matrizes (shape)

## Forma de matriz NumPy
- Referese ao número de elementos em cada dimensão.
- Use o atributo shape para retornar a tupla com as informações da forma.


In [1]:
import numpy as np

meu_array = np.array([
                      [21, 22, 23, 24], 
                      [25, 26, 27, 28]
                      ])

print(meu_array.shape)

print(f'Essa matriz possuir {meu_array.shape[0]} dimensões com {meu_array.shape[1]} elementos')

(2, 4)
Essa matriz possuir 2 dimensões com 4 elementos


In [2]:
import numpy as np

meu_array = np.array([21, 22, 23, 24, 25], ndmin=4)

print(meu_array)

print('A forma desse array é :', meu_array.shape)

[[[[21 22 23 24 25]]]]
A forma desse array é : (1, 1, 1, 5)


In [3]:
import numpy as np

meu_array = np.array([[
                       [[21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ],
                       [
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ]
                      ],
                      [
                       [[21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ],
                       [
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ]
                      ],
   
                      ] )

print(meu_array)

print('A forma desse array é :', meu_array.shape)

[[[[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]

  [[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]]


 [[[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]

  [[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]]]
A forma desse array é : (2, 2, 3, 5)


## NumPy Array Remodelagem
- Alterar a forma de uma matriz
- Pode se também adicionar ou remover dimensões ou alterar o número de elementos em cada dimensão.

### Remodelar de 1-D para 2-D

In [4]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 8, 9, 100, 110, 120])

novo_array = meu_array.reshape(5, 3)

print(novo_array)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100   8   9]
 [100 110 120]]


## Remodelar de 1-D para 3-D


In [5]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 8, 9, 100, 110, 120, 130, 140, 150])

novo_array = meu_array.reshape(2, 3, 3)

print(novo_array)

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100   8   9]
  [100 110 120]
  [130 140 150]]]


## Pode-se remodelar de qualquer forma desde que a quantidade de elementos seja  a mesma

In [6]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

novo_array = meu_array.reshape(3, 3)

print(novo_array)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## Dependendo da situação do resultado de um reshape pode ser uma cópia ou uma visão da matriz.

In [7]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = meu_array.reshape(2, 5)

print(novo_array.base)

[ 10  20  30  40  50  60  70  80  90 100]


In [8]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = meu_array.reshape(10)

print(novo_array.base)

[ 10  20  30  40  50  60  70  80  90 100]


In [9]:
novo_array.reshape(10).base

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Deixando o NumPy calcular o tamanho de uma das dimensões informa o valor -1

In [10]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = meu_array.reshape(2, -1)

print(novo_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


## Achatamento de matrizes
- Pode se usar reshape(-1) converter uma matriz multidimensional em uma matriz 1D.

In [11]:
import numpy as np

meu_array = np.array([[
                      [10, 20, 30], 
                      [40, 50, 60], 
                      [40, 50, 60]
                      ],
                      [
                      [10, 20, 30], 
                      [40, 50, 60], 
                      [40, 50, 60]
                      ]
                     ]
                      )
print(meu_array.shape)
novo_array = meu_array.reshape(-1)

print(novo_array)

(2, 3, 3)
[10 20 30 40 50 60 40 50 60 10 20 30 40 50 60 40 50 60]


## Achatamento de matrizes com a função flatten

In [12]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20],
              [21,22,23,24,25,26,27,28,29,30],
              [31,32,33,34,35,36,37,38,39,40]])
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [13]:
a.flatten('C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [14]:
a.flatten('F')

array([ 1, 11, 21, 31,  2, 12, 22, 32,  3, 13, 23, 33,  4, 14, 24, 34,  5,
       15, 25, 35,  6, 16, 26, 36,  7, 17, 27, 37,  8, 18, 28, 38,  9, 19,
       29, 39, 10, 20, 30, 40])

## Leituras Adicionais e Referências:

- Python Tutorial at W3Schools: https://www.w3schools.com/python/
- Python official documentation: https://docs.python.org/3/tutorial/index.html
- NumPy v1.19 Manual: https://numpy.org/doc/stable/